### ISSUE TITLE
Declare the parallelism support via sphinx extension metadata

### ISSUE THREAD

**Issue by webknjaz** [pypa/pypa-docs-theme#17]
Basically, the `setup()` function here should return a dict with a few keys.

Example: https://github.com/sphinx-contrib/sphinxcontrib-towncrier/blob/ff31e93/src/sphinxcontrib/towncrier/__init__.py#L183-L187.

Motivation: if you run Sphinx in a parallel mode (using `-j auto` CLI option), it explodes with:
```console
Warning, treated as error:
the pypa_theme extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
```

**Comment by pradyunsg** [comment]
PR welcome! ^>^

**Comment by webknjaz** [comment]
Maybe mark it with "good first issue" + "Hacktoberfest"?

**Comment by webknjaz** [comment]
@l1storez do you want to work on this task?

**Comment by l1storez** [comment]
yep
