### ISSUE TITLE
Change base theme to Furo?

### ISSUE THREAD

**Issue by pradyunsg** [pypa/pypa-docs-theme#18]
I've been spending a lot of time around Sphinx documentation stuff lately, and have a suggestion to make regarding our documentation theme (partly from my recent experience revamping pypa/packaging.python.org#627).

Suggestion: Let's switch to [Furo](pradyunsg.me/furo/quickstart) for our base theme here. I think it'll help our documentation overall (especially pip and packaging.python.org), since it's better at surfacing the documentation structure and has better navigational capabilities throughout.

Pros:

- Provides structured, clear sidebar navigation.
- Responsive!
- Has a fairly more "modern" design.
- Has a right sidebar that provides in-page navigation.
- Dark mode. :)

Cons:

- Not python-docs-theme, which distances us from CPython documentation.

/cc @ncoghlan @dstufft @theacodes since they were fairly active in the original discussion for the creation of this theme.

**Comment by theacodes** [comment]
I prefer to stick closely to the upstream python docs theme, but I no
longer have much of stake here.

**Comment by pradyunsg** [comment]
There's now https://github.com/pypa/packaging.python.org/pull/791, for migrating packaging.python.org to Furo, and pip's documentation has already been moved to Furo. Looking at #8, these were the only 2 projects that are using this theme.

**Comment by ichard26** [comment]
FYI, [pypa/bandersnatch does use this theme](https://bandersnatch.readthedocs.io/en/latest/).

**Comment by jeanas** [comment]
I would really love this since some of the guides are quite long and Furo's right sidebar with the TOC of the current page is super helpful for reading those.

**Comment by willingc** [comment]
@pradyunsg It would be awesome to update this theme to be more in line with the python dev guide.

**Comment by astrojuanlu** [comment]
I see the dev guide uses Furo at the moment: https://github.com/python/devguide/blob/e95f9085085c580923a883fa15574428e108ba4a/conf.py#L39

**Comment by jeanas** [comment]
Now that packaging.python.org uses Furo (https://github.com/pypa/packaging.python.org/issues/1354), this issue is done — and I guess the whole repository should be archived.

**Comment by pradyunsg** [comment]
This can definitely be closed!

**Comment by pradyunsg** [comment]
https://github.com/search?utf8=%E2%9C%93&q=pypa_docs_theme++org%3Apypa&type=code

Hmm... archiving this might indeed make sense.

**Comment by jeanas** [comment]
There seem to be no objections to archiving…

**Comment by chrysle** [comment]
@pradyunsg I'd be in favour, too, but can't do it, as PyPUG editors do not have admin access to this repo.
