### ISSUE TITLE
Quick Search's "Go" Button is not properly placed/padded

### ISSUE THREAD

**Issue by pradyunsg** [pypa/pypa-docs-theme#3]
The button is below the text box. I guess if it's on the same line or padded a bit, it'll look nicer?

<img width="252" alt="screen shot 2017-06-15 at 10 09 34 am" src="https://user-images.githubusercontent.com/3275593/27165881-a8224736-51b4-11e7-8fa0-8ee7f791768a.png">

**Comment by jonparrott** [comment]
Actually we should just remove the search from the sidebar and rely on the one on the topbar like CPython. Sent a PR here: https://github.com/pypa/python-packaging-user-guide/pull/324

**Comment by pradyunsg** [comment]
Sounds good to me. ^.^
