### ISSUE TITLE
Improving the Sidebar TOC

### ISSUE THREAD

**Issue by pradyunsg** [pypa/pypa-docs-theme#4]
As it stands, the Table of Contents in the sidebar looks a little weird. While it does provide everything that it should, the way it is currently styled does not really feel polished. 

I feel that there's inconsistent spacing, colours are used in a slightly confusing manner and text styling could be used for adding emphasis.

<img width="247" alt="screen shot 2017-06-15 at 11 00 44 am" src="https://user-images.githubusercontent.com/3275593/27166697-2879e3f8-51ba-11e7-9c5c-294ed5f1b811.png">

**Comment by pradyunsg** [comment]
Obviously, this is a subjective thing but I guess most people would agree.

**Comment by jonparrott** [comment]
Happy to accept a pull request to tweak this. Just send it over with
screenshot. :)

**Comment by pradyunsg** [comment]
Sure, I guess I can get around to doing this today. ^.^

> Just send it over with screenshot. :)

Roger that!

**Comment by jonparrott** [comment]
Thanks! I'm gonna try to focus on content now that the theme and structure
are settled.

**Comment by pradyunsg** [comment]
@jonparrott I didn't come around to doing this. Sorry for the delay. :/

**Comment by jonparrott** [comment]
No worries. Take your time. It'll still be here. :)
