### ISSUE TITLE
Tracking which PyPA projects have switched

### ISSUE THREAD

**Issue by pradyunsg** [pypa/pypa-docs-theme#7]
Would it make sense to keep track of which PyPA projects switch over to this theme, here or in the README?

**Comment by jonparrott** [comment]
Yes, I'll try to get to this Friday during my time on this project.

**Comment by pradyunsg** [comment]
Awesome! I'm willing to help out with ticking off items from the list. :)

**Comment by jonparrott** [comment]
Closing in favor of #8. :)
