### ISSUE TITLE
Limit body / site width?

### ISSUE THREAD

**Issue by Ivoz** [pypa/pypa-docs-theme#9]
Text taking up the whole screen makes it so much harder to read and process. Honestly even though I can see why you want to integrate the branding with python.org, it kinda sucks that all the UX advantages carefully designed into RTD has to go with it.

This is one of the no-brainer things that the RTD theme gets right. (And, I guess, that python.org still gets horribly wrong)

I'd advocate something like
```
div.body {
    max-width: 60em;
}

body {
    max-width: 80em;
}
```

Which looks like ![this](https://user-images.githubusercontent.com/199266/30000942-c6108f00-90c0-11e7-98ac-6e14c2340db3.png)

**Comment by jonparrott** [comment]
I'm definitely open to this, but I'd prefer this to be done upstream in the Python doc theme.

**Comment by pradyunsg** [comment]
@jonparrott Could pypa adopt this first and then demonstrating that there's genuine gains, one could push for upstream pydoc-theme to adopt these changes?

**Comment by jonparrott** [comment]
I'd be open to that, but since @Ivoz feels so strongly I'd suggest taking this directly upstream and I'm curious if there is already an open issue about it.

**Comment by pradyunsg** [comment]
> I'd be open to that

Great to know. :)

> I'm curious if there is already an open issue about it.

Me too. I'll try to find it if it exists.

> @Ivoz feels so strongly I'd suggest taking this directly upstream

@Ivoz -- are you willing to do so? If so, please do. :)

**Comment by pradyunsg** [comment]
@jonparrott I'm a little jobless tomorrow; I'll take a shot at this?

**Comment by jonparrott** [comment]
Go for it
